### ISSUE TITLE
During git pull of k/k if the references changes, try again sooner

### ISSUE THREAD

**Issue by dims** [kubernetes/publishing-bot#162]
Currently when we encounter the issue below ... we end up waiting for `interval` worth of time before trying again. We should try sooner than that as this is just an intermittent issue.

```
E0213 19:10:04.033361       1 publisher.go:396] failed to fetch at /go-workspace/src/k8s.io/kubernetes: reference has changed concurrently
I0213 19:10:04.043938       1 main.go:181] Failed to run publisher: failed to fetch at /go-workspace/src/k8s.io/kubernetes: reference has changed concurrently
```

**Comment by nikhita** [comment]
> We should try sooner than that as this is just an intermittent issue.

The flake hasn't been fixed yet but we try again within 5 mins in #166.
