### ISSUE TITLE
Move list of degenerated non-mainline merge commits to rules file

### ISSUE THREAD

**Issue by nikhita** [kubernetes/publishing-bot#180]
This list of commits is now hardcoded in our scripts: https://github.com/kubernetes/publishing-bot/pull/179, which means the bot needs to be redeployed each time we update the list.

It'll be easier to handle it and avoid redeploying if we move the list to the rules file.

**Comment by nikhita** [comment]
I can take a look at this, but only after KubeCon...

**Comment by nikhita** [comment]
Given that we have the `mergecommitblocker` plugin enabled in k/k (https://github.com/kubernetes/test-infra/pull/12783), I don't think this is really needed. Let's revisit this if we ever decide to disable the plugin (maybe problems with feature branches) or other instances of the bot need this feature.

**Comment by nikhita** [comment]
Reopening since this is still an issue: https://github.com/kubernetes/publishing-bot/pull/209

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
You may have another merge commit to deal with (ref: https://github.com/kubernetes/kubernetes/pull/89364)

https://github.com/kubernetes/test-infra/pull/17037 should prevent this from happening again

**Comment by spiffxp** [comment]
/assign @nikhita 
To put this on your radar
