### ISSUE TITLE
go mod pseudo version uses wrong timestamp

### ISSUE THREAD

**Issue by sttts** [kubernetes/publishing-bot#186]
We use `TZ=GMT git show -q --pretty='format:v0.0.0-%cd-%h' --date='format:%Y%m%d%H%M%S' --abbrev=12` to get the time stamp of the last commit. But this does not work, `TZ=GMT` has no influence and we get (probably) the timezone of the last commit.

**Comment by nikhita** [comment]
It needs to be `TZ=GMT git show -q --pretty='format:v0.0.0-%cd-%h' --date='format-local:%Y%m%d%H%M%S' --abbrev=12`

**Comment by liggitt** [comment]
https://stackoverflow.com/a/41032442/54696 might work

**Comment by sttts** [comment]
I tried the `-local` variants and it did not help.

**Comment by nikhita** [comment]
Added a commit https://github.com/kubernetes/publishing-bot/pull/185/commits/c68decee94451c900f2613c59caaa34d023f471c

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/publishing-bot/pull/185

/close
