### ISSUE TITLE
sync-tags adds an empty commit when pseudoversion doesn't change

### ISSUE THREAD

**Issue by nikhita** [kubernetes/publishing-bot#187]
Example: https://github.com/kubernetes/api/commit/7cf5895f2711098d7d9527db0a4a49fb0dff7de2

The pseudoversion for apimachinery doesn't change in the above case, but sync-tags still adds an empty commit. This isn't harmful, but is redundant. 

We should be able to avoid add that by checking the version by `go list -m -json k8s.io/apimachinery` and the expected pseudoversion.

/assign
will look over the weekend, don't have time to work on this + test it before then

**Comment by liggitt** [comment]
given https://github.com/kubernetes/publishing-bot/issues/215, I'm not sure this is still true, and if it is, I think we may actually want this behavior
