### ISSUE TITLE
Remove no-op replace directives from go.mod files

### ISSUE THREAD

**Issue by liggitt** [kubernetes/publishing-bot#214]
If the require and replace directive for a dependency match after running `go mod tidy`, drop the replace directive, since it is a no-op and confuses consumers

/assign

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/publishing-bot/pull/207

**Comment by dims** [comment]
cc @akhilerm

**Comment by dims** [comment]
context: https://github.com/kubernetes/kubernetes/issues/123933
