### ISSUE TITLE
Consider forcing a diff in go.mod when syncing semver tags

### ISSUE THREAD

**Issue by liggitt** [kubernetes/publishing-bot#215]
As part of sync-tags, we update go.mod files to refer to tagged releases of dependencies. This results in a tag-specific commit/SHA for most repos. This is desired, so that go resolves that sha to that specific semver tag.

If a repo has no peer dependencies (like k8s.io/apimachinery), no change is required to the go.mod file, so it is possible for multiple tags to be created pointing to the same commit/sha (like [v0.17.0](https://github.com/kubernetes/apimachinery/releases/tag/v0.17.0) and [v0.17.1-beta.0](https://github.com/kubernetes/apimachinery/releases/tag/v0.17.1-beta.0)).

While this is functionally correct (nothing breaks), it is confusing if go resolves a sha or non-semver tag (like kubernetes-1.17.0) to an unexpected semver tag (like v0.17.1-beta.0), even if it is equivalent content.

In sync-tags, when syncing a semver tag, if we also added a comment like "# Corresponds to Kubernetes v1.17.0", this would force a diff in all go.mod files, force a tag-specific commit, and reduce confusion in sha/non-semver resolution.

xref https://github.com/kubernetes/kubernetes/issues/84372#issuecomment-564562164

**Comment by nikhita** [comment]
/remove-lifecycle rotten

this would be nice to have
/assign

**Comment by benmoss** [comment]
I just ran into this while trying to automate vendoring via the script in https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-521493597

Here's a repro of the unexpected behavior:

```
$ go mod download -json k8s.io/controller-manager@kubernetes-1.19.1
{
        "Path": "k8s.io/controller-manager",
        "Version": "v0.19.3-rc.0",
        "Info": "/home/cesium/go/pkg/mod/cache/download/k8s.io/controller-manager/@v/v0.19.3-rc.0.info",
        "GoMod": "/home/cesium/go/pkg/mod/cache/download/k8s.io/controller-manager/@v/v0.19.3-rc.0.mod",
        "Zip": "/home/cesium/go/pkg/mod/cache/download/k8s.io/controller-manager/@v/v0.19.3-rc.0.zip",
        "Dir": "/home/cesium/go/pkg/mod/k8s.io/controller-manager@v0.19.3-rc.0",
        "Sum": "h1:j4Np5Ap5bUm7dWf+YpdtEO7onPh+bapRVyvDuX7+moA=",
        "GoModSum": "h1:dCndTiYrx486QGBfE/bGUQ+a70s8LUaBM8cCXtaVJ1E="
}
```
