### ISSUE TITLE
Upgrade module to go1.17

### ISSUE THREAD

**Issue by cpanato** [kubernetes/publishing-bot#248]
There is any reason that we cannot bump the bot to use ~go1.16~ go1.17?

If there is nothing against we can update it.

**Comment by cpanato** [comment]
i will assign to myself to work on that if that is ok

/assign

/kind feature

**Comment by cpanato** [comment]
cc @nikhita

**Comment by nikhita** [comment]
> There is any reason that we cannot bump the bot to use go1.16?

I think we can update to use go1.16 :+1:
