### ISSUE TITLE
Create a tool to update publishing-bot rules for new releases

### ISSUE THREAD

**Issue by nikhita** [kubernetes/publishing-bot#252]
See https://github.com/kubernetes/sig-release/pull/1504 for more context.

The publishing-bot copies/publishes code from [staging directories](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io) to their [own repos](https://github.com/search?q=topic%3Ak8s-staging+org%3Akubernetes&type=Repositories). The configuration for how the branches should be published are defined in the `master` branch of the main k/k repo: https://github.com/kubernetes/kubernetes/blob/master/staging/publishing/rules.yaml

For example, in this code snippet - https://github.com/kubernetes/kubernetes/blob/6572fe4d90173a1e97fda3e0cc28acc95e3f560a/staging/publishing/rules.yaml#L197-L209:

- The code in the `release-1.21` branch of the [client-go staging directory](https://github.com/kubernetes/kubernetes/tree/release-1.21/staging/src/k8s.io/client-go) is published to the [`release-1.21` branch](https://github.com/kubernetes/client-go/tree/release-1.21) of the client-go repo.
- The go.mod for the `release-1.21` branch of the client-go repo uses the `release-1.21` of api and apimachinery repos as dependencies.

This issue involves creating a new tool in Go (can go in the cmd/ directory) to update rules automatically. For example, the tool should automatically update rules.yaml in k/k to add the new branches for `release-1.21` like in https://github.com/kubernetes/kubernetes/pull/100616.

Adding new branches would basically involve copying over the `master` branch contents and updating the branch name. Additionally, the `go: <version>` field can be added to new branches too.

**Comment by dims** [comment]
@kubernetes/release-managers Any of the release folks interested in picking up karma in publishing-bot, please peek!

**Comment by nikhita** [comment]
cc @navidshaikh

**Comment by xmudrii** [comment]
Might be fixed by #253
