### ISSUE TITLE
Support running publishing bot for containerd

### ISSUE THREAD

**Issue by akhilerm** [kubernetes/publishing-bot#320]
Currently the publishing-bot is centred towards running only on the [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/) repo. We want to run publishing bot on the [containerd/containerd](https://github.com/containerd/containerd) repo to publish the [`api/`](https://github.com/containerd/containerd/tree/main/api) directory from containerd to a new `containerd/api` repository. 

Following are the list of changes that must be made to so that this can be achieved without breaking the existing publishing bot workflow for k8s:

- [x] add support for branch names containing "/" as containerd uses `release/1.6` https://github.com/kubernetes/publishing-bot/pull/319
- [x] workflow to test the changes in publishing bot https://github.com/kubernetes/publishing-bot/pull/334 https://github.com/kubernetes/test-infra/pull/29118
- [x] support configurable main branch name https://github.com/kubernetes/publishing-bot/pull/324
- [x] support for multiple subdirectories in rules https://github.com/kubernetes/publishing-bot/pull/337
- [x] updating debian base image and backport to support `git-filter-repo` https://github.com/kubernetes/publishing-bot/pull/336 https://github.com/kubernetes/publishing-bot/pull/351
- [ ] change `filter-branch` to `filter-repo` #369 
- [ ] modify handling go mod related changes so that containerd specific changes can be done to go mod
- [ ] modify tagging logic so that tagging can be done as per containerd needs also
- [ ] add checks to ensure only newly created containerd tags are pushed and old tags/refs etc are not pushed to the containerd/api repo.

**Comment by BenTheElder** [comment]
Personally: I would really suggest considering just making containerd/api a go package / module instead.

The staging hack is not something Kubernetes can reconsider easily, but it can cause a lot of problems with IDEs etc (e.g. gopls won't support multiple modules without go.work) and it allows you to develop libraries without thinking as much about breaking changes versus if you consumed it as a library yourself ...

**Comment by akhilerm** [comment]
@BenTheElder Sorry for the delay in response.

For the containerd repo, it wont cause an issue with IDEs. The workflow that is in `containerd/containerd` for contributing and also the code organization in containerd repo will not change. We will not have a staging like directory in containerd. Just the `/api` directory and some dependent directories will be made available as `containerd/api` repo.  The containerd/containerd will be consuming the apis from the directory itself. Only projects which need to use just the containerd api will be importing and using the `containerd/api` module. 


> I would really suggest considering just making containerd/api a go package / module instead.

This was earlier tried in containerd . Ref: https://github.com/containerd/containerd/pull/5716. But didnt work out and had to revert the module changes, here. Ref: https://github.com/containerd/containerd/pull/6439

**Comment by BenTheElder** [comment]
> just the /api directory and some dependent directories will be made available as containerd/api repo.

I still don't recommend this because it means you're not experiencing how other users will experience using the package, which makes it too easy to ignore breaking changes etc.

> This was earlier tried in containerd . Ref: https://github.com/containerd/containerd/pull/5716. But didnt work out and had to revert the module changes, here. Ref: https://github.com/containerd/containerd/pull/6439

I mean actually moving it out to another repo.

**Comment by akhilerm** [comment]
> I mean actually moving it out to another repo.

Didnt get this part. Do you mean to completely move the api to another repository and then import `containerd/api` in `containerd/containerd`

**Comment by BenTheElder** [comment]
Yes.

**Comment by akhilerm** [comment]
@BenTheElder That will cause issue with tagging and using the containerd/api in `containerd/containerd` as it will involve back and forth tagging between the repositories to use a latest release version in containerd/containerd. 

Hence following the publishing-bot approach, as it will handle tagging also and containerd community will not have to change their workflow. 

Only consumers of containerd/api will have to import the new module instead of `containerd/containerd` as a whole.

**Comment by akhilerm** [comment]
@BenTheElder Do you have more thoughts on this?
