### ISSUE TITLE
rewrite verify-publishing-bot.py in go

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/publishing-bot#345]
... so we can avoid requiring users to have python3 and install pyyaml to run `make verify`

I think this would actually be relatively straightforward, but I wanted to get feedback first.

Also while the script is in kubernetes/kubernetes, I figured this issue tracker might have better visibility.

https://github.com/kubernetes/kubernetes/blob/master/hack/verify-publishing-bot.py

Thoughts @nikhita @cpanato @dims?

**Comment by BenTheElder** [comment]
I think we could put something under k/k hack/tools similar to ncpu and invoke it with a thin shell script.

**Comment by ShivamTyagi12345** [comment]
The standalone script is fine for converting to go. I will make a PR for this issue

/ assign

**Comment by nitishchauhan0022** [comment]
@BenTheElder Do we need to change this as well https://github.com/kubernetes/kubernetes/blob/master/hack/verify-flags-underscore.py.

**Comment by BenTheElder** [comment]
No, the issue isn't python so much as python that depends on external packages the contributor must install to lint.

The other way to handle this would be to automate proper isolated package management but in this case I think writing it in go will be more maintainable for the project.

**Comment by 9bany** [comment]
Can i working on this issue @BenTheElder ?

**Comment by BenTheElder** [comment]
Yes, please do :-)

**Comment by 9bany** [comment]
How can I test this script? Do you have any idea? @BenTheElder

**Comment by BenTheElder** [comment]
Usually to verify a linter works I'd add a temporary commit with changes to whatever it is linting that are expected to make it fail. Then later the test commit can be dropped following review

**Comment by verma-kunal** [comment]
Hey @9bany , just wanted to know whether you are actively working on this issue or is it open to work?

**Comment by verma-kunal** [comment]
Hey @BenTheElder , to be sure on this, we have to replace this `.py` file right?

**Comment by ShivamTyagi12345** [comment]
> Hey @BenTheElder , to be sure on this, we have to replace this `.py` file right?

Hey @verma-kunal I missed the track on this , I see that I had already converted a fair portion of this code to code. Please feel free to use this if you dont want to start from scratch
https://gist.github.com/ShivamTyagi12345/1eb784ce9956a4ee0b4d160df43da057

**Comment by verma-kunal** [comment]
> Hey @verma-kunal I missed the track on this as I juggling travelling and work, I see that I had already converted a fair portion of this code to Go. Please feel free to use this if you dont want to start from scratch https://gist.github.com/ShivamTyagi12345/1eb784ce9956a4ee0b4d160df43da057

Hey Shivam, thanks for sharing this!

**Comment by sbdtu5498** [comment]
@BenTheElder can you please test the PR? The go portion is working fine, I have tested it locally. The only remaining piece is to run complete make verify. I did make quick-verify but it didn't include the verify-publishing-bot portion. Let me know if any other changes are required.

**Comment by sbdtu5498** [comment]
**cc:** @BenTheElder. Gentle reminder. Can you please take a look at the PR? Didn't disturb you as you were on vacation. Hope you had a great one. If you are back, kindly take a look whenever you would be free. Thanks!

**Comment by palnabarun** [comment]
@sbdtu5498 I have left some comments in the PR.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/118727 has outstanding comments

https://github.com/kubernetes/kubernetes/issues/117821#issuecomment-1854825296 we're down to just this and one other verify script not working OOTB for contributors on mac or otherwise opting into dockerized `make verify` (`build/run.sh make verify`).

**Comment by SD-13** [comment]
@akhilerm I would like to resurrect the PR and continue the work

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/125801 should merge soon with the fix, thanks @akhilerm

**Comment by akhilerm** [comment]
/close 
Fixed in https://github.com/kubernetes/kubernetes/pull/125801
