### ISSUE TITLE
Guidance requested: sub-modules go.mod and relative path resolution

### ISSUE THREAD

**Issue by thockin** [kubernetes/publishing-bot#347]
These k/k staging sub-modules are clearly broken:

https://github.com/kubernetes/code-generator/blob/master/examples/go.mod#L53-L57
https://github.com/kubernetes/kms/blob/master/internal/plugins/mock/go.mod#L25-L29

They happen to work when you use them in a GOPATH, which is required for other reasons TODAY, but will eventually not be required. Once GOPATH is properly dead, these will fail.

We *should* be reifying the `..` paths into real versions.  E.g. something converts https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kms/go.mod#L27-L32 into https://github.com/kubernetes/kms/blob/master/go.mod#L27-L31 - we need that same transformation for sub-modules.

Is this something the promoter bot should handle? 

xref https://github.com/kubernetes/kubernetes/pull/117920

**Comment by akhilerm** [comment]
Isnt the issue same as https://github.com/kubernetes/publishing-bot/issues/331 ?

**Comment by thockin** [comment]
LOL, I have no memory of filing that!
