### ISSUE TITLE
Improve PVC cleanup procedure for publishing-bot

### ISSUE THREAD

**Issue by akhilerm** [kubernetes/publishing-bot#364]
The current PVC cleanup process https://github.com/kubernetes/publishing-bot/blob/master/production.md#how-do-i-clean-up-the-pvc has one issue:
- If the new pod comes up faster than before the old PVC is completely deleted. The new pod will start using the old PVC which is in Terminating state, thus preventing the PVC from getting deleted and failing to do the cleanup.

One solution to solve this is via scaling down the `publisher` ReplicaSet, so that the pod is deleted first. and then we delete the PVC. This ensures proper deletion of PVC. The replicaset can be scaled up after the creation of PVC, and thus the new pod will use the fresh volume.

The problem with the above solution is additional permissions would have to be granted so that the scale can be patched on the replica set. Currently there is less permission to scale the replica
```
Error from server (Forbidden): replicasets.apps "publisher" is forbidden: User "<email>" cannot patch resource "replicasets/scale" in API group "apps" in the namespace "publishing-bot": requires one of ["container.replicaSets.updateScale" "container.replicaSets.update"] permission(s).
```

**Comment by akhilerm** [comment]
@ameukam Can you add  `replicasets/scale` subresource to the associated role ?

**Comment by ameukam** [comment]
> @ameukam Can you add `replicasets/scale` subresource to the associated role ? I think its still a manual process, couldnt find a terraform script that adds this permissions to the publishing-bot namespace.

@akhilerm you can patch this [role](https://github.com/kubernetes/k8s.io/blob/main/infra/gcp/bash/namespaces/namespace-user-role.yml#L15) to include this subresource.
