### ISSUE TITLE
Warning for memory limit of init container when deploying publishing bot

### ISSUE THREAD

**Issue by akhilerm** [kubernetes/publishing-bot#365]
The default configurationfor the init container of the publishing bot, uses a fractional value ([1.6Gi](https://github.com/kubernetes/publishing-bot/blob/master/artifacts/manifests/podspec.yaml#L17)) for the memory limit.  This causes a warning when the  publishing-bot is deployed to a cluster
```
spec.template.spec.initContainers[0].resources.limits[memory]: fractional byte value "1717986918400m" is invalid, must be an integer
```

A valid memory limit value for the init container should be identified and used in the default configuration

**Comment by ArkaSaha30** [comment]
Hi @akhilerm, I will take this up. 
/assign
