### ISSUE TITLE
Add support for removing branches in update-rules

### ISSUE THREAD

**Issue by akhilerm** [kubernetes/publishing-bot#377]
The `update-rules` command is used to add new branches to the  publishing-bot [rules](https://github.com/kubernetes/kubernetes/blob/master/staging/publishing/rules.yaml).  Ref: https://github.com/kubernetes/publishing-bot/tree/master/cmd/update-rules

We also have a use-case of removing rules of EOL branches similar to https://github.com/kubernetes/kubernetes/pull/116456/commits/43c841fa567626f52758a2c602071e862681ccce. 

The `update-rules` command can be modified to have a new flag , which when provided will remove the corresponding branch from the rules file.

**Comment by mohitsharma-in** [comment]
@akhilerm  Can i pick this up ?

**Comment by akhilerm** [comment]
sure. Thank you. 
/assign @mohitsharma-in
