### ISSUE TITLE
Enhance `rules.yaml` release branch validation to decouple from changes in k/k `master`

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/publishing-bot#433]
### Issue

We removed the `legacy-cloud-providers` staging repo in https://github.com/kubernetes/kubernetes/pull/124767 on k/k `master`, which immediately broke the rule validation ([`pull-publishing-bot-validate`](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124829/pull-publishing-bot-validate/1789915699716558848)) for all supported release branches.

### Solution

- We only validate the rules for the actual release branch when running on a `release-x.y` branch. 
- Continue to validate all rules when running on `master`

cc @kubernetes/release-engineering

**Comment by cpanato** [comment]
sounds good to me this approach
